version: "3.4"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=db_user
      - DB_PASS=super_awesome_password
      - DB_NAME=database

  database:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=super_awesome_password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
